##############################
# Netlify configuration file #
##############################

[build]
base = "react/"
publish = "dist/"
command = "vite build"

[build.environment]
NODE_VERSION = "20.14.0"