##############################
# Netlify configuration file #
##############################

[build]
base = "/"
publish = "dist/"
command = "npm run build --omit=dev"

[build.environment]
NODE_VERSION = "20.14.0"